source "https://supermarket.chef.io"

metadata

cookbook 'apt'
cookbook 'build-essential'
cookbook 'git'
cookbook 'users'
cookbook 'ruby_build'
cookbook 'database'
cookbook 'postgresql', '~> 3.4.20'
cookbook 'nginx', '~> 2.7.6'
cookbook 'unicorn', '~> 2.0.0'
